import type { Child } from "./types";
import type {
  ReportChartPoint,
  ReportContextSection,
  ReportDashboardStat,
  ReportData,
  ReportHighlight,
  ReportTimelineRow,
} from "./reporting";
import { getAgeLabelFromDob } from "./utils";

export interface ReportPdfPayload {
  title: string;
  subtitle: string;
  generatedAtLabel: string;
  patientSummary: string;
  dashboardStats: ReportPdfStat[];
  highlights: ReportPdfHighlight[];
  charts: ReportPdfChart[];
  contextSections: ReportPdfSection[];
  timeline: ReportPdfTimelineRow[];
}

interface ReportPdfStat {
  label: string;
  value: string;
  detail?: string;
}

interface ReportPdfHighlight {
  tone: "alert" | "caution" | "info";
  title: string;
  detail: string;
}

interface ReportPdfChart {
  title: string;
  primaryLabel: string;
  secondaryLabel?: string;
  points: ReportPdfChartPoint[];
}

interface ReportPdfChartPoint {
  label: string;
  primaryValue: number;
  secondaryValue?: number;
}

interface ReportPdfSection {
  title: string;
  emptyText: string;
  rows: ReportPdfSectionRow[];
}

interface ReportPdfSectionRow {
  title: string;
  meta?: string;
  detail?: string;
}

interface ReportPdfTimelineRow {
  dateTime: string;
  eventType: string;
  details: string;
  note?: string;
}

function mapStats(stats: ReportDashboardStat[]): ReportPdfStat[] {
  return stats.map((stat) => ({
    label: stat.label,
    value: stat.value,
    detail: stat.detail,
  }));
}

function mapHighlights(highlights: ReportHighlight[]): ReportPdfHighlight[] {
  return highlights.map((highlight) => ({
    tone: highlight.tone,
    title: highlight.title,
    detail: highlight.detail,
  }));
}

function mapPoints(points: ReportChartPoint[]): ReportPdfChartPoint[] {
  return points.map((point) => ({
    label: point.label,
    primaryValue: point.primaryValue,
    secondaryValue: point.secondaryValue,
  }));
}

function mapSections(sections: ReportContextSection[]): ReportPdfSection[] {
  return sections.map((section) => ({
    title: section.title,
    emptyText: section.emptyText,
    rows: section.rows.map((row) => ({
      title: row.title,
      meta: row.meta,
      detail: row.detail,
    })),
  }));
}

function mapTimeline(rows: ReportTimelineRow[]): ReportPdfTimelineRow[] {
  return rows.map((row) => ({
    dateTime: row.dateTime,
    eventType: row.eventType,
    details: row.details,
    note: row.note,
  }));
}

export function buildReportPdfPayload(input: {
  child: Child;
  startDate: string;
  endDate: string;
  data: ReportData;
}): ReportPdfPayload {
  const { child, startDate, endDate, data } = input;

  return {
    title: `${child.name}'s Health Log`,
    subtitle: `${startDate} to ${endDate}`,
    generatedAtLabel: `Generated by Tiny Tummy · ${new Date().toLocaleDateString()}`,
    patientSummary: `${child.name} · DOB ${child.date_of_birth} · ${getAgeLabelFromDob(child.date_of_birth)} · Diet ${child.feeding_type}`,
    dashboardStats: mapStats(data.dashboardStats),
    highlights: mapHighlights(data.highlights),
    charts: [
      {
        title: "Stool Output (Last 7 Days)",
        primaryLabel: "Stools",
        secondaryLabel: "No-poop days",
        points: mapPoints(data.chartData.stoolOutput),
      },
      {
        title: "Feed Activity (Last 7 Days)",
        primaryLabel: "Sessions",
        secondaryLabel: "Logged ml",
        points: mapPoints(data.chartData.feedActivity),
      },
    ],
    contextSections: mapSections(data.contextSections),
    timeline: mapTimeline(data.timeline),
  };
}
